# Generated by Django 4.2.6 on 2023-11-26 20:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_foro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crearforo',
            name='contenido',
            field=ckeditor.fields.RichTextField(max_length=1500, verbose_name='Contenido del Foro'),
        ),
    ]
