# Generated by Django 4.2.6 on 2023-11-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_foro', '0002_alter_crearforo_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crearforo',
            name='contenido',
            field=models.TextField(max_length=1500, verbose_name='Contenido del Foro'),
        ),
    ]
