# Generated by Django 4.2.6 on 2023-11-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_foro', '0004_remove_crearforo_contenido_contenido_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido',
            name='author',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='category',
        ),
        migrations.AddField(
            model_name='crearforo',
            name='contenido',
            field=models.CharField(default='Bienvenido a este foro!', max_length=1500, verbose_name='Contenido del Foro'),
        ),
        migrations.DeleteModel(
            name='Comentarios',
        ),
        migrations.DeleteModel(
            name='Contenido',
        ),
    ]
